#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

bash -n "${root}/run.sh"
bash -n "${root}/mcp-config.sh" "${root}/tests/test_provider_mcp_config.sh"
grep -q '^MIT License$' "${root}/../LICENSE"
grep -q 'Copyright (c) 2026 Nick Whyte' "${root}/../LICENSE"
if grep -q 'Nick Watts' "${root}/../LICENSE" "${root}/../NOTICE"; then exit 1; fi
grep -q 'Apache License, Version 2.0' "${root}/../NOTICE"
test -f "${root}/vendor/paseo/LICENSE"
grep -q '^ingress: true$' "${root}/config.yaml"
grep -q '^version: "0.1.15"$' "${root}/config.yaml"
grep -q '^panel_icon: mdi:code-braces$' "${root}/config.yaml"
if grep -q '^ingress_port:' "${root}/config.yaml"; then exit 1; fi
if grep -q '^panel_admin:' "${root}/config.yaml"; then exit 1; fi
grep -q 'type: homeassistant_config' "${root}/config.yaml"
grep -q 'ha_mcp_url' "${root}/config.yaml"
grep -q 'ha_mcp_url: url?' "${root}/config.yaml"
grep -q 'codex_remote_control: true' "${root}/config.yaml"
grep -q '^hassio_api: true$' "${root}/config.yaml"
grep -q '^hassio_role: manager$' "${root}/config.yaml"
if grep -q '^privileged:' "${root}/config.yaml"; then exit 1; fi
if grep -q 'SYS_ADMIN' "${root}/config.yaml" "${root}/run.sh"; then exit 1; fi
grep -q '^apparmor: false$' "${root}/config.yaml"
test ! -e "${root}/apparmor.txt"
if grep -q 'check_codex_sandbox\|bubblewrap\|writable_roots\|network_access' "${root}/run.sh"; then exit 1; fi
grep -q 'sandbox_mode = "danger-full-access"' "${root}/run.sh"
if grep -q 'force_device_login_on_start' "${root}/config.yaml"; then exit 1; fi
if grep -Eq '^[[:space:]]*(host_network|full_access|docker_api):[[:space:]]*true' "${root}/config.yaml"; then exit 1; fi
grep -q '^\[features\]$' "${root}/run.sh"
grep -q 'web_search_request = true' "${root}/run.sh"
grep -q 'codex features list' "${root}/run.sh"
grep -q 'PASEO_SCRATCH_DIR=/tmp/paseo-work' "${root}/run.sh"
grep -q 'default_tools_approval_mode = "writes"' "${root}/run.sh"
grep -q 'injectIntoAgents' "${root}/run.sh"
grep -q 'command -v paseo' "${root}/run.sh"
grep -q 'XDG_STATE_HOME' "${root}/run.sh"
grep -q 'GH_CONFIG_DIR' "${root}/run.sh"
grep -q "[$]{HOME}/\\.ssh" "${root}/run.sh"
grep -q 'GH_CONFIG_DIR=/data/paseo-home/.config/gh' "${root}/Dockerfile"
grep -q 'COPILOT_HOME=/data/paseo-home/.copilot' "${root}/Dockerfile"
grep -q 'COPILOT_CACHE_HOME=/data/paseo-home/.cache/copilot' "${root}/Dockerfile"
grep -q 'PASEO_HOSTNAMES=true' "${root}/run.sh"
grep -q 'CLAUDE_CONFIG_DIR' "${root}/run.sh"
grep -q 'has("codex_remote_control")' "${root}/run.sh"
grep -q 'paseo daemon start --foreground' "${root}/run.sh"
grep -q 'paseo daemon stop --force --timeout 3' "${root}/run.sh"
grep -q 'lock_cmd' "${root}/run.sh"
grep -q 'codex-cli\\ \*' "${root}/run.sh"
grep -q 'codex app-server --help' "${root}/run.sh"
grep -q 'codex remote-control --help' "${root}/run.sh"
grep -q 'codex login status' "${root}/run.sh"
grep -q 'codex remote-control start --json' "${root}/run.sh"
grep -q 'codex app-server daemon version' "${root}/run.sh"
grep -q 'packages/standalone' "${root}/run.sh"
if grep -q 'codex remote-control pair' "${root}/run.sh"; then exit 1; fi
if grep -Eq '^[[:space:]]*codex login --device-auth' "${root}/run.sh"; then exit 1; fi
grep -q 'command -v claude' "${root}/run.sh"
grep -q 'command -v opencode' "${root}/run.sh"
grep -q 'command -v pi' "${root}/run.sh"
grep -q 'command -v cursor-agent' "${root}/run.sh"
grep -q 'cursor_agent_version=' "${root}/run.sh"
grep -q 'command -v copilot' "${root}/run.sh"
grep -q 'copilot_version=' "${root}/run.sh"
grep -q 'copilot --version 2>&1' "${root}/run.sh"
grep -q 'command -v gh' "${root}/run.sh"
grep -q 'gh --version' "${root}/run.sh"
grep -q 'SUPERVISOR_TOKEN' "${root}/run.sh"
grep -q 'SUPERVISOR_ENDPOINT=' "${root}/run.sh"
grep -q 'SUPERVISOR_TOKEN is missing' "${root}/run.sh"
grep -q 'command -v ha' "${root}/run.sh"
grep -q 'ha help' "${root}/run.sh"
grep -q 'ensure_root_ssh_path' "${root}/run.sh"
grep -q 'readlink -f' "${root}/run.sh"
grep -q 'ln -s' "${root}/run.sh"
if grep -Eq 'migrat|cmp -s|mv --|rmdir "\$\{root_ssh\}"' "${root}/run.sh" "${root}/DOCS.md" "${root}/CHANGELOG.md"; then exit 1; fi
grep -q 'GH_CONFIG_DIR=/data/paseo-home/.config/gh' "${root}/DOCS.md"
grep -q '/data/paseo-home/.ssh' "${root}/DOCS.md"
grep -q '/data/paseo-home/.copilot' "${root}/DOCS.md"
grep -q '/data/paseo-home/.config/cursor' "${root}/DOCS.md"
grep -q 'copilot login --device-code' "${root}/DOCS.md"
grep -q 'cursor-agent login' "${root}/DOCS.md"
grep -q '/api/health' "${root}/run.sh"
grep -q 'paseo project create /config --json' "${root}/run.sh"
grep -q 'paseo --version' "${root}/Dockerfile"
grep -q 'PASEO_WEB_UI_DIST_DIR=/opt/hass-paseo-web-ui' "${root}/Dockerfile"
grep -q 'SHELL=/bin/bash' "${root}/Dockerfile"
grep -q 'export SHELL=/bin/bash' "${root}/run.sh"
grep -q "CODEX_VERSION=\${CODEX_VERSION}" "${root}/Dockerfile"
grep -q 'githubcli-archive-keyring.gpg' "${root}/Dockerfile"
grep -q '6084d5d7bd8e288441e0e94fc6275570895da18e6751f70f057485dc2d1a811b' "${root}/Dockerfile"
grep -q 'findutils gawk gh git' "${root}/Dockerfile"
grep -q 'fd-find' "${root}/Dockerfile"
grep -q 'python3-venv' "${root}/Dockerfile"
grep -q 'rsync' "${root}/Dockerfile"
grep -q 'xz-utils' "${root}/Dockerfile"
grep -q 'yq' "${root}/Dockerfile"
grep -q 'ln -s /usr/bin/fdfind /usr/local/bin/fd' "${root}/Dockerfile"
grep -q '@anthropic-ai/claude-code@' "${root}/Dockerfile"
grep -q 'opencode-ai@' "${root}/Dockerfile"
grep -q '@mariozechner/pi-coding-agent@' "${root}/Dockerfile"
grep -q '@github/copilot@' "${root}/Dockerfile"
grep -q 'CURSOR_AGENT_VERSION=' "${root}/Dockerfile"
grep -q 'agent-cli-package.tar.gz' "${root}/Dockerfile"
grep -q 'b73b59854762535c0fc20d7ccc51c3b5a356a851491088d60a362be48750f53c' "${root}/Dockerfile"
grep -q 'fb7bc635be6172ebcf68f907fd9217e3614da51916455c6d7fdb66690997884c' "${root}/Dockerfile"
grep -q 'sha256sum -c' "${root}/Dockerfile"
grep -q 'ARG HA_CLI_VERSION=5.5.0' "${root}/Dockerfile"
grep -q 'ha_amd64' "${root}/Dockerfile"
grep -q 'ha_aarch64' "${root}/Dockerfile"
grep -q 'HA_CLI_SHA256_AMD64' "${root}/Dockerfile"
grep -q 'HA_CLI_SHA256_AARCH64' "${root}/Dockerfile"
grep -q 'ha help' "${root}/Dockerfile"
grep -q 'codex login --device-auth' "${root}/DOCS.md"
grep -q 'allow 172.30.32.2' "${root}/nginx.conf"
grep -q 'deny all' "${root}/nginx.conf"
grep -q "map [$]http_x_ingress_path [$]paseo_ingress_path" "${root}/nginx.conf"
grep -q "map [$]http_x_ingress_path [$]paseo_ingress_path_valid" "${root}/nginx.conf"
grep -q "if ([$]paseo_ingress_path_valid = 0)" "${root}/nginx.conf"
grep -q "sub_filter /__PASEO_INGRESS__ [$]paseo_ingress_path" "${root}/nginx.conf"
if grep -Eq "^[[:space:]]*(proxy_set_header X-Ingress-Path|sub_filter /__PASEO_INGRESS__|sub_filter '</head>').*[$]http_x_ingress_path" "${root}/nginx.conf"; then exit 1; fi
grep -q 'sub_filter_once off' "${root}/nginx.conf"
grep -q 'location ~\*' "${root}/nginx.conf"
grep -q 'sub_filter_types text/css application/javascript text/javascript application/json application/manifest+json;' "${root}/nginx.conf"
grep -q '__PASEO_INITIAL_DAEMON_CONNECTION__' "${root}/nginx.conf"
grep -q '/__PASEO_INGRESS__/manifest.json' "${root}/patches/0001-ingress-base-url-build.patch"
grep -q '/__PASEO_INGRESS__/apple-touch-icon.png' "${root}/patches/0001-ingress-base-url-build.patch"
grep -q 'PASEO_COMMIT: "9400a49af670fdb5db4af58e73f8df98588dbea9"' "${root}/build.yaml"
grep -q 'HA_CLI_VERSION: "5.5.0"' "${root}/build.yaml"
grep -q 'HA_CLI_SHA256_AMD64:' "${root}/build.yaml"
grep -q 'HA_CLI_SHA256_AARCH64:' "${root}/build.yaml"
grep -q 'daemon-endpoints.ingress.test.ts' "${root}/patches/0002-ingress-websocket-path.patch"
grep -q "if (path === '//')" "${root}/patches/0003-expo-router-root-path.patch"
grep -q 'expo-router/package.json' "${root}/Dockerfile"
grep -q '0003-expo-router-root-path.patch' "${root}/Dockerfile"
workflow="${root}/../.github/workflows/build.yaml"
grep -q 'submodules: recursive' "${workflow}"
grep -q 'packages: write' "${workflow}"
grep -q 'linux/amd64' "${workflow}"
grep -q 'linux/arm64' "${workflow}"
grep -q 'inputs.version' "${workflow}"
grep -q 'default: "0.1.15"' "${workflow}"
grep -q 'PI_MCP_ADAPTER_VERSION: "1.5.1"' "${root}/build.yaml"
grep -q 'PI_MCP_ADAPTER_VERSION=1.5.1' "${workflow}"
grep -q 'pi-mcp-adapter@' "${root}/Dockerfile"
grep -q 'mcp-config.sh' "${root}/Dockerfile"
grep -q 'configure_provider_mcp' "${root}/run.sh"
grep -q 'ensure_pi_mcp_adapter' "${root}/run.sh"
grep -q 'PI_CODING_AGENT_DIR' "${root}/run.sh"
grep -q 'home_assistant' "${root}/mcp-config.sh"
grep -q 'opencode.*opencode.json' "${root}/mcp-config.sh"
grep -q 'mcpServers' "${root}/mcp-config.sh"
grep -q 'tools' "${root}/mcp-config.sh"
grep -q 'GITHUB_REPOSITORY_OWNER.*addon-hass-paseo' "${workflow}"
grep -q 'COPILOT_CLI_VERSION=1.0.83' "${workflow}"
grep -q 'CURSOR_AGENT_VERSION=2026.09.02-c22c1a3' "${workflow}"
grep -q 'HA_CLI_VERSION=5.5.0' "${workflow}"
grep -q 'HA_CLI_SHA256_AMD64=fb2e2177bd7bc014f029b807cd1cc7d74484ecfed1e90d5f9b2a61d65ff5393d' "${workflow}"
grep -q 'HA_CLI_SHA256_AARCH64=af390ab7f91a8135668ace7b1425d8e53800b6a1fc3b36fc588df701d2ab3db5' "${workflow}"

if [[ -f "${root}/vendor/paseo/.git" || -d "${root}/vendor/paseo/.git" ]]; then
  test "$(git -C "${root}/vendor/paseo" rev-parse HEAD)" = "9400a49af670fdb5db4af58e73f8df98588dbea9"
  git -C "${root}/vendor/paseo" apply --check "${root}/patches/0001-ingress-base-url-build.patch"
  git -C "${root}/vendor/paseo" apply --check "${root}/patches/0002-ingress-websocket-path.patch"
fi

echo "static checks passed"
