#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

bash -n "${root}/run.sh"
grep -q '^ingress: true$' "${root}/config.yaml"
if grep -q '^ingress_port:' "${root}/config.yaml"; then exit 1; fi
if grep -q '^panel_admin:' "${root}/config.yaml"; then exit 1; fi
grep -q 'type: homeassistant_config' "${root}/config.yaml"
grep -q 'ha_mcp_url' "${root}/config.yaml"
grep -q 'ha_mcp_url: url?' "${root}/config.yaml"
grep -q 'codex_remote_control: true' "${root}/config.yaml"
if grep -q 'force_device_login_on_start' "${root}/config.yaml"; then exit 1; fi
if grep -Eq '^[[:space:]]*(host_network|full_access|docker_api):[[:space:]]*true' "${root}/config.yaml"; then exit 1; fi
grep -q 'network_access = false' "${root}/run.sh"
grep -q 'writable_roots = \["/config"\]' "${root}/run.sh"
grep -q 'default_tools_approval_mode = "writes"' "${root}/run.sh"
grep -q 'injectIntoAgents' "${root}/run.sh"
grep -q 'command -v paseo' "${root}/run.sh"
grep -q 'command -v bwrap' "${root}/run.sh"
grep -q 'XDG_STATE_HOME' "${root}/run.sh"
grep -q 'CLAUDE_CONFIG_DIR' "${root}/run.sh"
grep -q 'has("codex_remote_control")' "${root}/run.sh"
grep -q 'paseo daemon start --foreground' "${root}/run.sh"
grep -q 'paseo daemon stop --force --timeout 3' "${root}/run.sh"
grep -q 'lock_cmd' "${root}/run.sh"
grep -q 'codex-cli\\ \*' "${root}/run.sh"
grep -q 'codex app-server --help' "${root}/run.sh"
grep -q 'codex remote-control --help' "${root}/run.sh"
grep -q 'codex login status' "${root}/run.sh"
grep -q 'codex remote-control start --json' "${root}/run.sh"
grep -q 'codex app-server daemon version' "${root}/run.sh"
grep -q 'packages/standalone' "${root}/run.sh"
if grep -q 'codex remote-control pair' "${root}/run.sh"; then exit 1; fi
if grep -Eq '^[[:space:]]*codex login --device-auth' "${root}/run.sh"; then exit 1; fi
grep -q 'command -v claude' "${root}/run.sh"
grep -q 'command -v opencode' "${root}/run.sh"
grep -q 'command -v pi' "${root}/run.sh"
grep -q '/api/health' "${root}/run.sh"
grep -q 'paseo project create /config --json' "${root}/run.sh"
grep -q 'paseo --version' "${root}/Dockerfile"
grep -q 'PASEO_WEB_UI_DIST_DIR=/opt/hass-paseo-web-ui' "${root}/Dockerfile"
grep -q "CODEX_VERSION=\${CODEX_VERSION}" "${root}/Dockerfile"
grep -q 'bubblewrap' "${root}/Dockerfile"
grep -q 'fd-find' "${root}/Dockerfile"
grep -q 'python3-venv' "${root}/Dockerfile"
grep -q 'rsync' "${root}/Dockerfile"
grep -q 'xz-utils' "${root}/Dockerfile"
grep -q 'yq' "${root}/Dockerfile"
grep -q 'ln -s /usr/bin/fdfind /usr/local/bin/fd' "${root}/Dockerfile"
grep -q '@anthropic-ai/claude-code@' "${root}/Dockerfile"
grep -q 'opencode-ai@' "${root}/Dockerfile"
grep -q '@mariozechner/pi-coding-agent@' "${root}/Dockerfile"
grep -q 'codex login --device-auth' "${root}/DOCS.md"
grep -q 'allow 172.30.32.2' "${root}/nginx.conf"
grep -q 'deny all' "${root}/nginx.conf"
grep -q 'sub_filter_once off' "${root}/nginx.conf"
grep -q 'location ~\*' "${root}/nginx.conf"
grep -q 'sub_filter_types text/css application/javascript text/javascript application/json application/manifest+json;' "${root}/nginx.conf"
grep -q '__PASEO_INITIAL_DAEMON_CONNECTION__' "${root}/nginx.conf"
grep -q 'PASEO_COMMIT: "9400a49af670fdb5db4af58e73f8df98588dbea9"' "${root}/build.yaml"
grep -q 'daemon-endpoints.ingress.test.ts' "${root}/patches/0002-ingress-websocket-path.patch"
workflow="${root}/../.github/workflows/build.yaml"
grep -q 'submodules: recursive' "${workflow}"
grep -q 'packages: write' "${workflow}"
grep -q 'linux/amd64' "${workflow}"
grep -q 'linux/arm64' "${workflow}"
grep -q 'inputs.version' "${workflow}"
grep -q 'GITHUB_REPOSITORY_OWNER.*addon-hass-paseo' "${workflow}"

if [[ -f "${root}/vendor/paseo/.git" || -d "${root}/vendor/paseo/.git" ]]; then
  test "$(git -C "${root}/vendor/paseo" rev-parse HEAD)" = "9400a49af670fdb5db4af58e73f8df98588dbea9"
  git -C "${root}/vendor/paseo" apply --check "${root}/patches/0001-ingress-base-url-build.patch"
  git -C "${root}/vendor/paseo" apply --check "${root}/patches/0002-ingress-websocket-path.patch"
fi

echo "static checks passed"
